### ISSUE TITLE
Richiesta info e informazioni per i contributori

### ISSUE THREAD

**Issue by MatteoGheza** [SITA-RegionePiemonte/csiatlante#3]
Salve, vorrei richiedere una **guida per contributori**  e una **roadmap**  su github, in modo da poter aiutare e 
_contribuire nel porting con nuove versioni di Qgis._ 
Grazie in anticipo e congratulazioni per quanto realizzato ad oggi.

**Comment by stefano-giorgi** [comment]
Buongiorno. La ringrazio per l'attenzione e mi scuso per il ritardo nella risposta. Il presente plugin è stato sostituito dalla nuova versione AtlanteWI. Può trovare maggiori informazioni al seguente indirizzo https://github.com/SITA-RegionePiemonte/CSIAtlanteWI . Cordiali saluti

**Comment by MatteoGheza** [comment]
La ringrazio per la risposta
